apps/PandABox-no-fmc-sfp2_udpontrig.app.ini
commit 215da527cfb22864cb96aaefc6dc6bfe227da6ee remove sfp3_sync block 
Don't use this at Soleil
This should also contain :
commit b4fce3c95b8536e59e5d8401a27e7c7981820f66 adding in state on reset of failing APP_NAME = PandABox-fmc_24vio build
commit 096dc6c790d8b54a4e211363035165b8e843b158 Added false path timing constraints for udpontrig
=> remove sfp3_sync block

targets/PandABox/hdl/encoders.vhd
Hi
I have implemented sign extension in the encoders.vhd to see negative numbers when we have encoders with less than 32 bits; this makes it coherent with the sign extension code in ssi_sniffer.vhd
=> Added sign extension to encoders.vhd to be coherent with ssi_sniffer.vhd

modules/seq/hdl/seq.vhd, modules/seq/hdl/sequencer_table.vhd, modules/seq/seq.timing.ini
`load_next` was introducing a 1 clock delay on getting the next line, stopping it working for a 1 clock tick PHASE2. The following clause was inserted in the past to activate it in PHASE1, but the logic was wrong, causing #41 
`(current_frame = next_frame and seq_sm = PHASE_1 and unsigned(PRESCALE) < to_unsigned(2,32) and (current_frame.time2 = 0 or current_frame.time2 = to_unsigned(1,32)))`
This PR moves the selection of `seq_raddr` into combinatorial logic backed by a clock process that is always updating `seq_raddr_next`
All tests passing
=> Fix sequencer to work with 1 clock tick PHASE2

common/hdl/defines/support.vhd, common/hdl/serial_engine_rx.vhd, common/hdl/shifter_in.vhd, common/templates/block_wrapper.vhd.jinja2, common/templates/hdl_timing.v.jinja2, common/templates/pcap_hdl_timing.v.jinja2, common/templates/top_defines.vhd.jinja2, etc/check_ipmi, modules/fmc_acq427/hdl/fmc_acq427_wrapper.vhd, modules/fmc_loopback/hdl/fmc_loopback_wrapper.vhd, modules/sfp_dls_eventr/hdl/sfp_dls_eventr_wrapper.vhd, old/tests/sim/panda_biss/bench/glbl.v, old/tests/sim/panda_slowctrl/bench/glbl.v, targets/PandABox/SlowFPGA/src/hdl/dcard_ctrl.vhd, targets/PandABox/blocks/inenc/inenc.block.ini, targets/PandABox/blocks/outenc/outenc.block.ini, targets/PandABox/hdl/biss_master.vhd, targets/PandABox/hdl/biss_slave.vhd, targets/PandABox/hdl/biss_sniffer.vhd, targets/PandABox/hdl/dcard_interface.vhd, targets/PandABox/hdl/encoders.vhd, targets/PandABox/hdl/encoders_block.vhd, targets/PandABox/hdl/ssi_master.vhd, targets/PandABox/hdl/ssi_slave.vhd, targets/PandABox/hdl/ssi_sniffer.vhd, targets/PandABox/hdl/ttlin_top.vhd, tests/hdl/top_defines.vhd
Possibility to choose between gray and binary encoding and signed/unsigned value for absolute encoders; default is unsigned binary. Description has been updated as per GTHIBAUX comment on PR #30, to show that this affects absolute and not incremental encoders. This pull request also solves issue #34 (position_sign_extension is not optional).
=> Encoder gray + signed/unsigned

Makefile, etc/load-panda-firmware, etc/panda-fpga.list
This is required to use the latest kernel version and should be merged at the same time that this [PR](https://github.com/PandABlocks/PandABlocks-rootfs/pull/18)
=> Adapt FPGA loading to use the FPGA manager

modules/pcap/hdl/pcap_dma.vhd
to fix issue #56: "Driver data overrun" error occured when the last DMA IRQ is too close to the completion IRQ.
=> pcap: fix driver overrun issue caused by the last 2 IRQs too close

modules/pcap/hdl/pcap_dma.vhd
Sorry to add a patch to the last PR #57, I found with ILA that the last change will make pcap_fsm jumping in ACTV-DMA-IS_FINISHED states before achieving the last IRQ state, as shown in this image: 
So I fixed it by this new PR.
=> pcap: avoid pcap_fsm jumping in ACTV/DMA states before last IRQ

common/hdl/finedelay.vhd, tests/sim/finedelay/bench/finedelay_tb.vhd
Additionally, the associated test bench was modified to print timing information. It can be run with `make run_sim_finedelay`
This fixes [issue 86](https://github.com/PandABlocks/PandABlocks-FPGA/issues/86)
The testbench shows the expected behavior, but this hasn't been tested in a Pandabox yet
=> finedelay: register ddr outputs to meet timing constraints

modules/pcap/pcap.timing.ini, modules/pcap/pcap_sim.py, tests/test_python_sim_timing.py
These changes fix the PCAP python simulation which were not working after #68.
An additional 2 TS delay was required on the DATA output.
Sum^2 capture entry was added.
With these changes all python_timing tests will now complete successfully.
=> Fixed the PCAP python simulation tests.

common/hdl/defines/top_defines.vhd, common/hdl/mmcm_clkmux.vhd, common/hdl/reg_top.vhd, common/python/configs.py, common/python/generate_app.py, common/templates/top_defines_gen.vhd.jinja2, modules/lvdsout/hdl/lvdsout_block.vhd, modules/lvdsout/lvdsout.block.ini, modules/pcap/hdl/pcap_frame_mode.vhd, modules/ttlout/hdl/ttlout_block.vhd, modules/ttlout/ttlout.block.ini, targets/PandABox/const/PandABox-clks_impl.xdc, tests/python/test_generate_app.py
- Autogenerate constants for options
- Add 'if-option' to allow filtering fields in block ini files
- Add fine delay option, a target or application can have it by adding the FPGA option 'fine_delay'
=> Optional finedelay

common/fpga.make, common/python/generate_app.py, common/python/generate_constants.py, common/templates/registers_server, modules/pcap/hdl/pcap_arming.vhd, modules/pcap/hdl/pcap_core.vhd, modules/pcap/hdl/pcap_core_ctrl.vhd, modules/pcap/hdl/pcap_dma.vhd, modules/pcap/hdl/pcap_top.vhd, tests/python/test_data/app-expected/config_d/registers
This change provide a new interrupt source when PCAP becomes active and enabled, if this condition happens in isolation, the block will not be switched (which was the default in every interrupt before this change).
Additionally, a driver compatibility register was added which is checked when the driver is loaded.
This fixes https://github.com/PandABlocks/PandABlocks-FPGA/issues/88
=> Add PCAP interrupt on PCAP.ENABLE high when armed and enabled

targets/PandABox/target-top.dts
Fix for USB on PandABox for PandABlocks v3 (Vivado 2020 and later).
With some help from @EmilioPeJu and the Xilinx wiki:
https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18842272/Zynq+Linux+USB+Device+Driver
we added a node for the usb-phy to the devicetree.
The corresponding change for the xu5 was not found to be necessary, as the USB already works fine with v3. Not sure about the ZedBoard but from recollection this did not work in the past, though USB support is not so useful for this target.
=> Fix for USB on PandABox

CONFIG.example, Makefile, common/fpga.make, common/python/generate_app.py, common/scripts/build_ip.tcl, common/scripts/build_ip_proj.tcl, common/templates/ip.make.jinja2, ip_defs/eth_mac.tcl, ip_defs/eth_phy.tcl, ip_defs/event_receiver_mgt.tcl, ip_defs/fifo_1K32.tcl, ip_defs/fifo_1K32_ft.tcl, ip_defs/fmc_acq427_dac_fifo.tcl, ip_defs/fmc_acq430_ch_fifo.tcl, ip_defs/fmc_acq430_sample_ram.tcl, ip_defs/fmcgtx.tcl, ip_defs/ila_0.tcl, ip_defs/ila_32x8K.tcl, ip_defs/pulse_queue.tcl, ip_defs/sfp_panda_sync.tcl, ip_defs/sfp_transmit_mem.tcl, ip_defs/sfpgtx.tcl, ip_defs/system_cmd_fifo.tcl, targets/PandABox/target_incl.tcl, targets/ZedBoard/target_incl.tcl, targets/xu5_st1/target_incl.tcl
* Allows for adding optional IP repos external to Vivado, so not all sites need to generate all IP for a particular target
* Does timestamp/dependency checking of each IP rather than build-once for each target as before, but will only regenerate the new IP when building new app
* At the expense of slightly longer runtime for IP product generation (c. 3-4 mins for no_fmc app, as opposed to 1-2 mins for all PandABox IPs) due to overhead from launching vivado multiple times (if anyone has an idea how to do this better, please suggest)
* Another side-effect is that `make edit_ips` will no longer show all IPs for a target, just those required for the app selected in CONFIG, but `make carrier_ip` can be run again for the other apps to fully populate the IP project.
=> Changes to build system to only generate IP required for App

common/hdl/defines/top_defines.vhd, common/hdl/mmcm_clkmux.vhd, modules/fmc_loopback/const/fmc_loopback_impl.xdc, modules/sfp_dls_eventr/const/sfp_event_receiver_impl.xdc, modules/sfp_dls_eventr/hdl/sfp_dls_eventr_wrapper.vhd, modules/sfp_dls_eventr/hdl/sfp_event_receiver.vhd, modules/sfp_loopback/const/sfp_loopback_impl.xdc, modules/sfp_panda_sync/const/sfp_panda_sync_impl.xdc, modules/sfp_panda_sync/hdl/sfp_panda_sync_mgt_interface.vhd, modules/sfp_panda_sync/hdl/sfp_panda_sync_transmit.vhd, modules/sfp_panda_sync/hdl/sfp_panda_sync_wrapper.vhd, modules/system/hdl/system_top.vhd, modules/system/system.block.ini, targets/PandABox/const/PandABox-clks_impl.xdc, targets/PandABox/hdl/PandABox_top.vhd
Having convinced myself that it is enough to declare the clocks as asynchronous groups with the `-include_generated_clocks` flag (given that the clocks are async and we don't make use of any advanced CDC constraints such as `max_delay -datapathonly`), I eventually conceded and re-added exclusive constraints for the multiplexed clocks (although not-strictly necessary) to appease the `report_cdc` tool. I decided to just use the auto-derived names of these clocks, rather than renaming them with `create_generated_clock` as this causes complications with the recovered clock name and the processing order of the constraint files by Vivado.
Also, for clean living, added synchronisers to some MGT derived signals which are used in the clock mux selection, and renamed clock signals for better …
=> Clocking changes to allow fine delay and recovered clock

modules/seq/hdl/seq.vhd, modules/seq/hdl/sequencer_double_table.vhd, modules/seq/hdl/sequencer_table.vhd, modules/seq/seq.timing.ini, modules/seq/seq_sim.py
- A new table can be loaded while a table without continuation mark is running, data can be loaded concurrently and when the new table is fully written, the sequencer switches inmediately without stopping
- bug fix: disabling the sequencer while loading a table was messing the table status, a test for this was added
- Tests were adapted to the modifications
=> Sequencer block modifications

modules/pcap/hdl/pcap_dma.vhd, targets/PandABox/bd/panda_ps.tcl
- state SWITCH_ADDR was deleted, as it is simpler to do the address switching in state IRQ
- a procedure to start the dma transaction was added reducing code duplication
- `switch_block` was renamed to a more meaningful name `buffer_full`
- Remove conditional code that wouldn't work anyways
=> pcap: simplify `pcap_dma`

common/hdl/axi_lite_slave.vhd
The following states were removed:
- State READ_START from the reading state machine
- State WRITE_START from the writing state machine
This achieves a simpler state machine and it is 1 clock faster, because now, the strobe signal is asserted in the transition from idle
=> Simplify axi_lite_slave and make it faster

common/hdl/encoders/encoders.vhd, modules/inenc/inenc.block.ini, modules/outenc/outenc.block.ini, modules/system/hdl/system_registers.vhd, modules/system/hdl/system_top.vhd
* Removed over-riding of protocol codes
* OUTENC forced to follow INENC for MONITOR cards
* Added checking of readback INENC and OUTENC codes
See also corresponding PR in SlowFPGA repO:
https://github.com/PandABlocks/PandABlocks-slowFPGA/pull/1
=> Tidy-up of encoders and slow interface

common/templates/registers_server, tests/python/test_data/app-expected/config_d/registers, tests/python/test_data_calc_extensions/app-expected/config_d/registers
This adds a new register *REG.NOMINAL_CLOCK which can safely be left to return the default value of 0 and adds some formatting changes.
This in part addresses issues #512 and PandABlocks/PandABlocks-server#8
=> Update common/templates/registers_server to match current server version

modules/pcap/pcap.block.ini, modules/pcap/pcap_sim.py
This addresses part of issues PandABlocks/PandABlocks-server#8 and #152
=> Rename SAMPLES to GATE_DURATION

modules/sfp_panda_sync/hdl/sfp_panda_sync_mgt_interface.vhd, modules/sfp_panda_sync/hdl/sfp_panda_sync_receiver.vhd, modules/sfp_panda_sync/hdl/sfp_panda_sync_transmit.vhd, modules/sfp_panda_sync/hdl/sfp_panda_sync_wrapper.vhd, modules/sfp_panda_sync/hdl/sim/pandaSync_rx_TB.vhd, modules/sfp_panda_sync/hdl/sim/pandaSync_tx_TB.vhd, modules/sfp_panda_sync/hdl/sim/run_xsim_rx.sh, modules/sfp_panda_sync/hdl/sim/run_xsim_tx.sh, modules/sfp_panda_sync/hdl/sim/xsim.tcl, modules/sfp_panda_sync/sfp_panda_sync.block.ini
Major change to PandASync protocol
* 8 bit-bus entries are transmitted each clock tick
* Packing as follows:
| BITS[7:0] | POS1[31:16] | K28.5  |
| BITS[7:0] | POS1[15:0]  | POS2[31:24] |
| BITS[7:0] | POS2[23:0]  |
| BITS[7:0] | POS3[31:8]  |
| BITS[7:0] | POS3[7:0]   | POS4[31:16] |
| BITS[7:0] | POS4[15:0]  | CHECKBYTE   |
CHECKBYTE currently holds either all zeros, or a sequence number (which is checked for consecutive values). It could also hold some kind of checksum but does not currently.
Remaining issues:
* Link still requires resetting manually after initialisation
* Bogus(?) protocol-error detected after plugging fibre, requires manual reset to clear
I tried adding a settling-time delay to hold the MGT in reset until after the link has stabilised. This has no effect for small …
=> Sync protocol changes

common/hdl/encoders/encoders_top.vhd, common/templates/block_ctrl.vhd.jinja2, common/templates/block_wrapper.vhd.jinja2, modules/fmc_24vio/hdl/fmc_24vio_wrapper.vhd, modules/fmc_acq427/hdl/fmc_acq427_wrapper.vhd, modules/fmc_acq430/hdl/fmc_acq430_wrapper.vhd, modules/fmc_loopback/hdl/fmc_loopback_wrapper.vhd, modules/lvdsout/hdl/lvdsout_top.vhd, modules/pcap/hdl/pcap_core_ctrl.vhd, modules/pcap/hdl/pcap_top.vhd, modules/sfp_eventr/hdl/sfp_dls_eventr_wrapper.vhd, modules/sfp_loopback/hdl/sfp_loopback_wrapper.vhd, modules/sfp_panda_sync/hdl/sfp_panda_sync_wrapper.vhd, modules/sfp_udpontrig/hdl/sfp_udpontrig_wrapper.vhd, modules/ttlin/hdl/ttlin_top.vhd, modules/ttlout/hdl/ttlout_top.vhd, modules/us_system/hdl/us_system_top.vhd, modules/zedboard_demo/hdl/zedboard_demo_top.vhd, tests/python/test_data/app-expected/hdl/lut_ctrl.vhd, tests/python/test_data/app-expected/hdl/lut_wrapper.vhd, tests/python/test_data_calc_extensions/app-expected/hdl/dummy_ctrl.vhd, tests/python/test_data_calc_extensions/app-expected/hdl/fmc_acq427_ctrl.vhd, tests/python/test_data_calc_extensions/app-expected/hdl/interval_ctrl.vhd
* write_ack now set in ctrl block and not wrapper
* read_ack over-riding removed for hardware blocks
* read_ack added to modules which did not have one previously
The only blocks which treat the `acks` differenently are `system` due to the slow FPGA registers, and `pcap` due to the DRV block.
NB: I checked this built for all zpkgs and tested one zpkg on hardware and it worked fine, but just noticed this is failing the python tests on PR. I think I can fix this before merging.
=> Remove over-riding of ctrl block ack ports where feasible

README.rst
The Code CI on the README hasn't been picking up that CI is passing. This changes the link to the badge to one that is updating correctly.
=> Fixed README badge

modules/pcap/hdl/pcap_dma.vhd
There is no reason to not start transfering to memory if we have more than 1 burst worth of data in the fifo.
=> Don't waste time in `pcap_dma`

common/fpga.make, targets/PandABox/etc/target-defs, targets/PandABox/target-top.dts, targets/PandABrick/etc/atsha240a-gen.py, targets/PandABrick/etc/target-defs, targets/ZedBoard/etc/target-defs, targets/xu5_st1/etc/target-defs, targets/xu5_st1/target-top.dts
At the moment only 2 targets define it:
PandABox: MAC from a qspi memory
PandABrick: MAC from a secure EEPROM
This is part of a solution for issue PandABlocks/PandABlocks-FPGA#167 and it's related to https://github.com/PandABlocks/PandABlocks-rootfs/pull/49
=> Allow each target to define the way to obtain its MAC address

common/python/configs.py, tests/python/test_data_calc_extensions/app-expected/config_d/config, tests/python/test_data_calc_extensions/interval/interval.block.ini
Adds functionality in the autogen framework to add an initial_value to param fields in block.ini files as described in the server documentation:
https://pandablocks.github.io/PandABlocks-server/master/config.html#field-type
Resolves #173
=> Initial value

targets/xu5_st1/etc/target-defs, targets/xu5_st1/target-top.dts
This change only affect target xu5_st1 but can be easily ported to others. The display controller is a SSD1306.
fbpad(a frame buffer terminal emulator) is expected to by provided by the rootfs.
=> xu5: show network status on the OLED display

modules/counter/counter.block.ini, modules/counter/counter.timing.ini, modules/counter/counter_sim.py, modules/counter/hdl/counter.vhd
- Setting the counter take precedence over a trigger event, that way the block will output the set value at least for one tick
- It is possible to set a value while the block is disabled (this allows to control the pos bus value without having to actually count)
- Timing tests were added for two cases: setting a value while enabled and setting a value while disabled
- Python counter simulation script was updated to consider the set register
=> counter: add register to set counter value

.github/workflows/code.yml
* Temporary measure to restore functioning CI
Using v3 as a work-around to avoid the error:
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
due to breaking change in v4:
https://github.com/actions/upload-artifact#breaking-changes
=> Update upload/download-artifact to v3

common/hdl/encoders/biss_sniffer.vhd, common/hdl/encoders/encoders.vhd, common/hdl/encoders/ssi_error_detect.vhd, common/hdl/encoders/ssi_master.vhd, common/hdl/encoders/ssi_sniffer.vhd, modules/inenc/inenc.block.ini
* Encoder loss deduced from serial data from encoder not clock
* Loss detection common to master and sniffer
* For BiSS, just check for clock at startup as CRC will check data
* integrity. Serial clock is needed to interpret data frame.
CONN signal for SSI and BISS sniffer modules was showing as 1 (connected) when nothing was plugged into DB9 connectors.
This was because the 'serial_link_detect' module was looking for the clock signal staying high for 5us to verify the link, and then checking for rising edges during the active period, following the first falling edge. The RS-485 line drivers read high on the line when nothing is connected, so it satisfied the first condition and the initial falling edge for the frame never arrives.
For SSI_master the CONN signal was previously hard-wired …
=> Fix for SSI and BiSS encoder modules to correctly detect encoder loss

.github/workflows/_make_zpkg.yml
Use tini to 'make zpkg' to avoid the process hanging.
=> Use tini to clean zombie processes
